export const HEADERS = {
	"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
	Connection: "keep-alive",
	"Cache-Control": "max-age=0",
	"sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
	"sec-ch-ua-mobile": "?0",
	"Upgrade-Insecure-Requests": "1",
	Origin: "https://dhlottery.co.kr",
	"Content-Type": "application/x-www-form-urlencoded",
	Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
	Referer: "https://dhlottery.co.kr/",
	"Sec-Fetch-Site": "same-site",
	"Sec-Fetch-Mode": "navigate",
	"Sec-Fetch-User": "?1",
	"Sec-Fetch-Dest": "document",
	"Accept-Language": "ko,en-US;q=0.9,en;q=0.8,ko-KR;q=0.7",
};
